#!/usr/bin/env python3

import sys


def parseInstruction(fileStream):
   
   for line in fileStream:
      line = line.rstrip()
      print(line)

def main():
   parseInstruction(sys.stdin)

if __name__ == "__main__":
   main()
